
project_id = "cmjsqliqmfpoxklunhqv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions.analyze-policy]
verify_jwt = false

[functions.search-weather-events]
verify_jwt = false
