project_id = "cmjsqliqmfpoxklunhqv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[[functions]]
[functions.analyze-policy]
verify_jwt = false

[[functions]]
[functions.search-weather-events]
verify_jwt = false