// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmjsqliqmfpoxklunhqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtanNxbGlxbWZwb3hrbHVuaHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MTA1MzMsImV4cCI6MjA1NDM4NjUzM30.Lvr9-Zgjk4dnN--JosWPWLuQZm5CIUafPkOQPVaMBI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);